### ISSUE TITLE
Added Contributing.md

### ISSUE THREAD

**Issue by Prakash-Haldar** [sameersrivastava13/Vaccine-Tracker-App#8] opened 2021-07-08 16:12 UTC
**This will provide the information in "READ ME"** . **For how to contribute in This project using GIT & GitHub**
_Assigned me this issue as DCP open source 2021_

**Comment by sameersrivastava13** [comment] 2021-07-10 06:45
hi @Prakash-Haldar. Actually we already have a [Contributing.md](https://github.com/sameersrivastava13/Vaccine-Tracker-App/blob/main/CONTRIBUTING.md) in our project. Please have a look and provide details what extra you can add in that. If you can add something more then ill assign this issue to you.

**Comment by Swathi-A469** [comment] 2021-07-11 07:12
Can I make a contribution on this read me fill

**Comment by Prakash-Haldar** [comment] 2021-07-11 07:14
The way to contribute include the : How to create pull request 
fork the repo , clone it , how to push .
This will help people to contribute to this project @sameersrivastava13

**Comment by swathi-469** [comment] 2021-07-11 07:31
Can I work on this issue ..I am beginner in open source ... please assign me

**Comment by Prakash-Haldar** [comment] 2021-07-11 10:11
@sameersrivastava13  Can I start working on this issue ?

**Comment by sameersrivastava13** [comment] 2021-07-12 15:25
> Can I work on this issue ..I am beginner in open source ... please assign me

@swathi-469 Assigning it to you. Start working on it.

**Comment by sameersrivastava13** [comment] 2021-07-12 15:27
> @sameersrivastava13 Can I start working on this issue ?

@Prakash-Haldar Actually just now I have assigned you another issue. Please complete that issue first and if @swathi-469 is not able to submit PR within 2 days then I'll assign it to you.

**Comment by sameersrivastava13** [comment] 2021-07-12 15:29
> The way to contribute include the : How to create pull request
> fork the repo , clone it , how to push .
> This will help people to contribute to this project @sameersrivastava13

ok go ahead @Prakash-Haldar . Assigning it to you.

**Comment by sameersrivastava13** [comment] 2021-07-12 15:30
> Can I work on this issue ..I am beginner in open source ... please assign me

@swathi-469 if @Prakash-Haldar is not able to submit PR within 2 days then I'll it to you. Till then you can explore other issues or wait for new beginner friendly issues.

**Comment by swathi-469** [comment] 2021-07-12 15:46
You already assigned it to me so I completed my work and ready to make my pull request.. please consider

**Comment by swathi-469** [comment] 2021-07-12 15:59
Shall i create a pull request

**Comment by sameersrivastava13** [comment] 2021-07-12 16:03
@swathi-469 actually @Prakash-Haldar created this issue and asked me to assign first before you. So you can wait for at least 24 hours if he doesn't make the PR then you can.

**Comment by sameersrivastava13** [comment] 2021-07-12 16:03
> Shall i create a pull request

@swathi-469 actually @Prakash-Haldar created this issue and asked me to assign first before you. So you can wait for at least 24 hours if he doesn't make the PR then you can.

**Comment by swathi-469** [comment] 2021-07-12 16:18
Ok sir

**Comment by Prakash-Haldar** [comment] 2021-07-12 17:16
Hey @swathi-469  I Think First of all you should Learn a Lit Bit about " Issue Made By admin" "Issue Made By Contributors" 
I remember  that today morning you do the same thing in mine assigned project & Also in Others one , I saw That The issue which was already assigned to someone or create by them you poke them to give it you  . Please Don't Create any mess .** Open source is a platform to learn ** Not a place of competition 
p.s: Please watch videos about open source issue section

**Closed as completed** 2021-07-12 17:25 UTC
Labels: documentation, No-Code, DCP'21, Level 0, Assigned

**Comment by swathi-469** [comment] 2021-07-12 17:49
I am very to new open-source contribution , so thought that I they create issue and we need to work on it . Later I realized that we can also create a new issue .. so sorry the trouble caused by me .
